Decoder
lookback/libavcodec pull request #3
Opened 2024-05-01 10:43 UTC by lookback-hugotunius

⚠️  This PR depends on #2 and needs to be rebased after #2 is merged. ⚠️ 

Implement support for decoding

2024-05-01 10:45 UTC, lookback-hugotunius commented on src/decoder.rs
> +        packet: &Packet,
I'm not sure how we should handle the lifetime on `Packet` here. The lifetime of the data is tied to the packet itself I suppose

2024-05-01 11:52 UTC, lolgesten requested changes

2024-05-01 11:52 UTC, lolgesten commented on src/lib.rs
> +impl Frame {
Let's call this `DecodedFrame` and move it into `decoder.rs`

2024-05-01 11:52 UTC, lolgesten commented on src/lib.rs
> +    pub unsafe fn data(&self) -> [*mut u8; sys::AV_NUM_DATA_POINTERS as usize] {
You don't really need unsafe here. Since the caller will need to unsafe to dereference the point or move it into C.

2024-05-01 11:52 UTC, lolgesten commented on src/lib.rs
> +        unsafe {
Double unsafe

2024-05-01 11:52 UTC, lolgesten commented on src/lib.rs
> +    pub fn stride(&self) -> [i32; sys::AV_NUM_DATA_POINTERS as usize] {
`strides` with an s... this is plural.

2024-05-01 11:52 UTC, lolgesten commented on src/lib.rs
> +    }
Instead of implementing these getters, we could just implement the frame trait from the encoder. That goes against my rename comments in the other PR.

2024-05-01 11:54 UTC, lookback-hugotunius commented on src/lib.rs
> +    pub unsafe fn data(&self) -> [*mut u8; sys::AV_NUM_DATA_POINTERS as usize] {
`unsafe` has two use cases:

1. Forcing the caller to use unsafe to call the function
2. Enabling certain capabilities

Here I think it's correct to have the function marked unsafe since there are requirements on the caller.

2024-05-01 11:55 UTC, lookback-hugotunius commented on src/lib.rs
> +        unsafe {
Yes true, I do think there's a slightly distinction between the unsafe on the function item and this block, see https://github.com/lookback/libavcodec/pull/3#discussion_r1586227832

2024-05-01 11:56 UTC, lookback-hugotunius commented on src/lib.rs
> +    }
That's a good point 👍 

However, there's still the complexity around returning the right type for `get_plane` /`data` namely figuring out the correct length for the slice

2024-05-01 14:53 UTC, lookback-hugotunius commented on src/lib.rs
> +            v if v == Self::AV_PIX_FMT_YUV420P as i32 => Self::AV_PIX_FMT_YUV420P,
We could use [`num_derive`](https://crates.io/crates/num-derive) maybe(assuming it's possible to integrate with bindgen)

2024-05-07 08:23 UTC, lookback-hugotunius commented on src/lib.rs
> +    pub unsafe fn data(&self) -> [*mut u8; sys::AV_NUM_DATA_POINTERS as usize] {
Btw, Rust agrees with me here, the pattern you are suggesting is due to become a warning in the future https://github.com/rust-lang/rfcs/pull/2585

2024-05-07 08:28 UTC, lookback-hugotunius commented on src/lib.rs
> +impl Frame {
I did this, but I'm not sure I like it. I think the symmetry libavcodec has where packet and frame are a single type and encoding is: frame -> packet while decoding is: packet -> frame is nice.

2024-05-07 11:54 UTC, lolgesten requested changes
Some discussion points

2024-05-07 11:54 UTC, lolgesten commented on src/decoder.rs
> +            assert!(!buf.is_null());
Is this a panic or an error?

2024-05-07 11:54 UTC, lolgesten commented on src/decoder.rs
> +        // retained in the decoder.
Can you document what happens with the buffer inside the packet here?

2024-05-07 11:54 UTC, lolgesten commented on src/decoder.rs
> +        vec.extend_from_slice(value);
This doesn't create the extra zeroes at the end. It has the capacity, but not the len.

2024-05-07 11:54 UTC, lolgesten commented on src/decoder.rs
> +    pub unsafe fn into_raw(mut self) -> *mut c_void {
Why is this pub?

2024-05-07 11:54 UTC, lolgesten commented on src/decoder.rs
> +    pub unsafe fn from_raw(ptr: *mut c_void) -> Self {
Ditto. Why pub?

2024-05-07 11:54 UTC, lolgesten commented on src/decoder.rs
> +            ) * self.height() as i32;
why is this `sys::av_image_get_linesize` when the `get_stride()` below uses `(*self.0).linesize`?

2024-05-07 11:54 UTC, lolgesten commented on src/decoder.rs
> +}
Not a fan of `Default` here because that becomes public API, which means anyone can instantiate a "useless" `DecodedFrame::default()`. Would prefer this to be an internal constructor.

2024-05-07 11:55 UTC, lookback-hugotunius commented on src/decoder.rs
> +        vec.extend_from_slice(value);
It calls `Self::new` below which does it

2024-05-07 11:57 UTC, lookback-hugotunius commented on src/decoder.rs
> +    pub unsafe fn into_raw(mut self) -> *mut c_void {
This and `from_raw` enables the user to use this frame with other C libraries that take an opaque pointer + a free function

2024-05-07 11:57 UTC, lookback-hugotunius commented on src/decoder.rs
> +    pub unsafe fn from_raw(ptr: *mut c_void) -> Self {
See above

2024-05-07 11:58 UTC, lookback-hugotunius commented on src/decoder.rs
> +            ) * self.height() as i32;
Good point, I suggest adopting `av_image_get_linesize` below too

2024-05-07 11:59 UTC, lookback-hugotunius commented on src/decoder.rs
> +}
Sure, internal is fine

2024-05-07 11:59 UTC, lookback-hugotunius commented on src/decoder.rs
> +        // retained in the decoder.
Yes

2024-05-07 12:00 UTC, lookback-hugotunius commented on src/decoder.rs
> +            assert!(!buf.is_null());
I was thinking it mostly fails in OOM situations and there's nothing much that can be done at that point, but it's a good point. I will consult the docs about when it can be NULL

2024-05-07 12:20 UTC, lolgesten commented on src/decoder.rs
> +        vec.extend_from_slice(value);
Alright

2024-05-07 12:20 UTC, lookback-hugotunius commented on src/decoder.rs
> +        // retained in the decoder.
See c39b715

2024-05-07 12:26 UTC, lookback-hugotunius commented on src/decoder.rs
> +}
Resolved in 3e6ec7e

2024-05-07 13:15 UTC, lolgesten approved these changes
Looks good!

2024-05-07 13:22 UTC, merged